# Generated by Django 2.1 on 2018-11-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181103_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sell',
            new_name='retail',
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
